[package]
name = "latticefold"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-crypto-primitives = { version = "0.4.0", default-features = false, features = ["sponge"] }
ark-ff = "0.4.2"
lattirust-arithmetic = { git="ssh://git@github.com/cknabs/lattirust.git", branch = "main"}
num-traits = "0.2.19"
rand = "0.8.5"
thiserror-no-std = { version = "2.0.2", default-features = false }

