[package]
name = "latticefold"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-crypto-primitives = { version = "0.4.0", default-features = false, features = [
    "sponge",
] }
ark-ff = { version = "0.4.2", default-features = false }
ark-std = { version = "0.4.0", default-features = false }
lattirust-arithmetic = { git = "ssh://git@github.com/NethermindEth/lattirust.git", branch = "main" }
libm = "0.2.8"
num-traits = "0.2.19"
rand = "0.8.5"
thiserror = "1.0.63"
