[package]
name = "latticefold"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-crypto-primitives = { version = "0.4.0", default-features = false, features = [
    "sponge",
] }
ark-ff = { version = "0.4.2", default-features = false }
ark-std = { version = "0.4.0", default-features = false }
lattirust-arithmetic = { git = "ssh://git@github.com/NethermindEth/lattirust.git", branch = "main" }
num-traits = "0.2.19"
rand = "0.8.5"
thiserror = "1.0.63"

[lints.clippy]
single_match = "warn"
single_match_else = "warn"
needless_match = "warn"
needless_late_init = "warn"
redundant_pattern_matching = "warn"
redundant_pattern = "warn"
redundant_guards = "warn"
collapsible_match = "warn"
match_single_binding = "warn"
match_same_arms = "warn"
match_ref_pats = "warn"
match_bool = "warn"
needless_bool = "warn"
implicit_clone = "warn"
[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "ajtai"
harness = false
