[workspace] 
members = [ "latticefold", "cyclotomic-rings"]
resolver = "2"

[workspace.dependencies]
ark-crypto-primitives = { version = "0.4.0", default-features = false, features = [
    "sponge",
] }
ark-ff = { version = "0.4.2", default-features = false }
ark-std = { version = "0.4.0", default-features = false }
lattirust-linear-algebra = { git = "ssh://git@github.com/NethermindEth/lattirust.git", branch = "Ivolkg/bumping", default-features = false }
lattirust-poly = { git = "ssh://git@github.com/NethermindEth/lattirust.git", branch = "Ivolkg/bumping", default-features = false }
lattirust-ring = { git = "ssh://git@github.com/NethermindEth/lattirust.git", branch = "Ivolkg/bumping", default-features = false }
