[package]
name = "ccs"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-relations = "0.4.0"
ark-std = "0.4.0"

lattirust-arithmetic = { version = "0.0.1-alpha", path = "../../lattirust/lattirust-arithmetic/" }
