[benchmarks]
goldilocks = [
    { x_len = 1, c = 6, w = 512, b = "128", l = 10,  b_small = 2, k = 7 },
    { x_len = 1, c = 7, w = 512, b = "256", l = 8,  b_small = 2, k = 8 },
    { x_len = 1, c = 8, w = 512, b = "512", l = 8,  b_small = 2, k = 9 },
    { x_len = 1, c = 8, w = 1024, b = "512", l = 8,  b_small = 2, k = 9 },
    { x_len = 1, c = 8, w = 2048, b = "256", l = 8,  b_small = 2, k = 8 },
    { x_len = 1, c = 9, w = 1024, b = "1024", l = 7,  b_small = 2, k = 10 },
    { x_len = 1, c = 9, w = 2048, b = "512", l = 8,  b_small = 2, k = 9 },
    { x_len = 1, c = 10, w = 512, b = "2048", l = 6,  b_small = 2, k = 11 },
    { x_len = 1, c = 10, w = 1024, b = "2048", l = 6,  b_small = 2, k = 11 },
    { x_len = 1, c = 11, w = 1024, b = "4096", l = 6,  b_small = 2, k = 12 },
    { x_len = 1, c = 11, w = 2048, b = "2048", l = 6,  b_small = 2, k = 11 },
    { x_len = 1, c = 12, w = 1024, b = "8192", l = 5,  b_small = 2, k = 13 },
    { x_len = 1, c = 13, w = 1024, b = "16384", l = 5,  b_small = 2, k = 14 },
    { x_len = 1, c = 13, w = 2048, b = "8192", l = 5,  b_small = 2, k = 13 },
    { x_len = 1, c = 14, w = 1024, b = "32768", l = 5,  b_small = 2, k = 15 },
    { x_len = 1, c = 14, w = 2048, b = "16384", l = 5,  b_small = 2, k = 14 },
    { x_len = 1, c = 15, w = 2048, b = "32768", l = 5,  b_small = 2, k = 15 },
    { x_len = 1, c = 16, w = 2048, b = "65536", l = 4,  b_small = 2, k = 16 },
]

starkprime = [
    { x_len = 1, c =  15, w = 1024, b = "1073741824", l = 9, b_small = 2, k = 30},
    { x_len = 1, c =  16, w = 1024, b = "4294967296", l = 8, b_small = 2, k = 32},
    { x_len = 1, c =  17, w = 2048, b = "8589934592", l = 8, b_small = 2, k = 33},
    { x_len = 1, c =  18, w = 2048, b = "17179869184", l = 8, b_small = 2, k = 34},
    { x_len = 1, c =  19, w = 2048, b = "34359738368", l = 8, b_small = 2, k = 35},
]

frog = [
    { x_len = 1, c =  5, w = 512, b = "8", l = 23, b_small = 2, k = 3},
    { x_len = 1, c =  9, w = 1024, b = "128", l = 10, b_small = 2, k = 7},
    { x_len = 1, c =  10, w = 1024, b = "256", l = 9, b_small = 2, k = 8},
    { x_len = 1, c =  12, w = 512, b = "1024", l = 7, b_small = 2, k = 10},
    { x_len = 1, c =  15, w = 1024, b = "4096", l = 6, b_small = 2, k = 12},
]

babybear = [
    { x_len = 1, c =  6, w = 1024, b = "512", l = 4, b_small = 2, k = 9},
    { x_len = 1, c =  7, w = 1024, b = "2048", l = 3, b_small = 2, k = 11},
    { x_len = 1, c =  8, w = 4096, b = "2048", l = 3, b_small = 2, k = 11},
    { x_len = 1, c =  9, w = 2048, b = "8192", l = 3, b_small = 2, k = 13},
    { x_len = 1, c =  10, w = 4096, b = "16384", l = 3, b_small = 2, k = 14},
]

[ajtai]
babybear = [
    { c = 1, w = 32768},
    { c = 2, w = 32768},
    { c = 3, w = 32768},
    { c = 4, w = 32768},
    { c = 5, w = 32768},
    { c = 6, w = 32768},
    { c = 1, w = 65536},
    { c = 2, w = 65536},
    { c = 3, w = 65536},
    { c = 4, w = 65536},
    { c = 5, w = 65536},
    { c = 6, w = 65536},
    { c = 1, w = 131072},
    { c = 2, w = 131072},
    { c = 3, w = 131072},
    { c = 4, w = 131072},
    { c = 5, w = 131072},
    { c = 6, w = 131072},
    { c = 1, w = 262144},
    { c = 2, w = 262144},
    { c = 3, w = 262144},
    { c = 4, w = 262144},
    { c = 5, w = 262144},
    { c = 6, w = 262144},
    { c = 1, w = 524288},
    { c = 2, w = 524288},
    { c = 3, w = 524288},
    { c = 4, w = 524288},
    { c = 5, w = 524288},
    { c = 6, w = 524288},
    { c = 1, w = 1048576},
    { c = 2, w = 1048576},
    { c = 3, w = 1048576},
    { c = 4, w = 1048576},
    { c = 5, w = 1048576},
    { c = 6, w = 1048576},
    { c = 12, w = 32768},
    { c = 13, w = 65536},
    { c = 13, w = 131072},
    { c = 14, w = 262144},
    { c = 14, w = 524288},
    { c = 15, w = 1048576},
]

goldilocks = [
    { c = 1, w = 32768},
    { c = 2, w = 32768},
    { c = 3, w = 32768},
    { c = 4, w = 32768},
    { c = 5, w = 32768},
    { c = 6, w = 32768},
    { c = 1, w = 65536},
    { c = 2, w = 65536},
    { c = 3, w = 65536},
    { c = 4, w = 65536},
    { c = 5, w = 65536},
    { c = 6, w = 65536},
    { c = 1, w = 131072},
    { c = 2, w = 131072},
    { c = 3, w = 131072},
    { c = 4, w = 131072},
    { c = 5, w = 131072},
    { c = 6, w = 131072},
    { c = 1, w = 262144},
    { c = 2, w = 262144},
    { c = 3, w = 262144},
    { c = 4, w = 262144},
    { c = 5, w = 262144},
    { c = 6, w = 262144},
    { c = 1, w = 524288},
    { c = 2, w = 524288},
    { c = 3, w = 524288},
    { c = 4, w = 524288},
    { c = 5, w = 524288},
    { c = 6, w = 524288},
    { c = 1, w = 1048576},
    { c = 2, w = 1048576},
    { c = 3, w = 1048576},
    { c = 4, w = 1048576},
    { c = 5, w = 1048576},
    { c = 6, w = 1048576},
    { c = 17, w = 32768},
    { c = 17, w = 65536},
    { c = 18, w = 131072},
    { c = 19, w = 262144},
    { c = 19, w = 524288},
    { c = 20, w = 1048576},
]

starkprime = [
    { c = 1, w = 32768},
    { c = 2, w = 32768},
    { c = 3, w = 32768},
    { c = 4, w = 32768},
    { c = 5, w = 32768},
    { c = 6, w = 32768},
    { c = 1, w = 65536},
    { c = 2, w = 65536},
    { c = 3, w = 65536},
    { c = 4, w = 65536},
    { c = 5, w = 65536},
    { c = 6, w = 65536},
    { c = 1, w = 131072},
    { c = 2, w = 131072},
    { c = 3, w = 131072},
    { c = 4, w = 131072},
    { c = 5, w = 131072},
    { c = 6, w = 131072},
    { c = 1, w = 262144},
    { c = 2, w = 262144},
    { c = 3, w = 262144},
    { c = 4, w = 262144},
    { c = 5, w = 262144},
    { c = 6, w = 262144},
    { c = 1, w = 524288},
    { c = 2, w = 524288},
    { c = 3, w = 524288},
    { c = 4, w = 524288},
    { c = 5, w = 524288},
    { c = 6, w = 524288},
    { c = 1, w = 1048576},
    { c = 2, w = 1048576},
    { c = 3, w = 1048576},
    { c = 4, w = 1048576},
    { c = 5, w = 1048576},
    { c = 6, w = 1048576},
    { c = 7, w = 131072},
    { c = 7, w = 262144},
    { c = 7, w = 524288},
    { c = 7, w = 1048576},
]

frog = [
    { c = 1, w = 32768},
    { c = 2, w = 32768},
    { c = 3, w = 32768},
    { c = 4, w = 32768},
    { c = 5, w = 32768},
    { c = 6, w = 32768},
    { c = 1, w = 65536},
    { c = 2, w = 65536},
    { c = 3, w = 65536},
    { c = 4, w = 65536},
    { c = 5, w = 65536},
    { c = 6, w = 65536},
    { c = 1, w = 131072},
    { c = 2, w = 131072},
    { c = 3, w = 131072},
    { c = 4, w = 131072},
    { c = 5, w = 131072},
    { c = 6, w = 131072},
    { c = 1, w = 262144},
    { c = 2, w = 262144},
    { c = 3, w = 262144},
    { c = 4, w = 262144},
    { c = 5, w = 262144},
    { c = 6, w = 262144},
    { c = 1, w = 524288},
    { c = 2, w = 524288},
    { c = 3, w = 524288},
    { c = 4, w = 524288},
    { c = 5, w = 524288},
    { c = 6, w = 524288},
    { c = 1, w = 1048576},
    { c = 2, w = 1048576},
    { c = 3, w = 1048576},
    { c = 4, w = 1048576},
    { c = 5, w = 1048576},
    { c = 6, w = 1048576},
    { c = 17, w = 32768},
    { c = 18, w = 65536},
    { c = 19, w = 131072},
    { c = 19, w = 262144},
    { c = 20, w = 524288},
    { c = 21, w = 1048576},
]
